### ISSUE TITLE
#if not pragma ...

### ISSUE THREAD

**Issue by msomp** [vjekob/bctechdays2022#6]
Hi Vjeko, 

I really like your new extension, thx for supporting our community.
Sometimes I use if not pragma in my projects, at the moment these are presented twice in the pragma-explorer.
Maybe you can change this in one of the next releases.

Thanks, Martin.

**Comment by louagej** [comment]
@msomp ,

There's an update already merged (14h ago) in the main. 
![Screenshot_20220915-123812_Chrome](https://user-images.githubusercontent.com/7229592/190383441-ed5ecdb5-224f-4bcd-9974-d56db7e77959.jpg)

So as soon a new build is performed, this should be solved. 

Regards, 
Job

**Comment by vdevmt** [comment]
Hi,
I think this bug hasn't been fixed yet.
Using #if not preprocessor, I get this result:

<img width="1344" height="193" alt="Image" src="https://github.com/user-attachments/assets/0c725194-65bd-4837-9801-42c98b7acc05" />

could you please check?
